/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Tests.AddElementToCollection;
import Tests.RunPythonScript;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.*;
import Utils.ResponseParser;
import java.nio.charset.Charset;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Niklaus
 */
public class MainWindow extends javax.swing.JFrame {
    private final String key;
    private final String projectId;
    private String currentSpiderID;
    /**
     * Creates new form MainWindow
     * @param key
     * @param projectId
     */
    public MainWindow(String key, String projectId) {
        this.key = key;
        this.projectId = projectId;
        initComponents();
        this.selectedProjectLabel.setText("Selected Project: " + projectId);
        this.apiKeyLabel.setText("API Key: " + key);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectsAndSpidersPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        spidersList = new javax.swing.JList();
        listSpidersBtn = new javax.swing.JButton();
        listResultsBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultArea = new javax.swing.JTextArea();
        saveResultBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        runSpiderBtn = new javax.swing.JButton();
        spiderNameField = new javax.swing.JTextField();
        spiderMessageLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        returnTestArea = new javax.swing.JTextArea();
        showLogBtn = new javax.swing.JButton();
        spiderIdField = new javax.swing.JTextField();
        selectedProjectLabel = new javax.swing.JLabel();
        apiKeyLabel = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(spidersList);

        listSpidersBtn.setText("List Spiders for selected Project");
        listSpidersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listSpidersBtnActionPerformed(evt);
            }
        });

        listResultsBtn.setText("List Results for selected Spider");
        listResultsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listResultsBtnActionPerformed(evt);
            }
        });

        resultArea.setColumns(20);
        resultArea.setRows(5);
        jScrollPane1.setViewportView(resultArea);

        saveResultBtn.setText("Save to DB");
        saveResultBtn.setEnabled(false);
        saveResultBtn.setPreferredSize(new java.awt.Dimension(179, 23));
        saveResultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveResultBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(listSpidersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(listResultsBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveResultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listSpidersBtn)
                    .addComponent(listResultsBtn)
                    .addComponent(saveResultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        projectsAndSpidersPanel.addTab("List Projects and Spiders", jPanel1);

        runSpiderBtn.setText("Run Spider now");
        runSpiderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runSpiderBtnActionPerformed(evt);
            }
        });

        spiderNameField.setText("Enter Spider to be scheduled");

        returnTestArea.setColumns(20);
        returnTestArea.setRows(5);
        jScrollPane3.setViewportView(returnTestArea);

        showLogBtn.setText("Show Log");
        showLogBtn.setEnabled(false);
        showLogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showLogBtnActionPerformed(evt);
            }
        });

        spiderIdField.setText("Enter current Spider ID");
        spiderIdField.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addComponent(spiderMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                            .addComponent(spiderNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(spiderIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(showLogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(runSpiderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(185, 185, 185))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runSpiderBtn)
                    .addComponent(spiderNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showLogBtn)
                    .addComponent(spiderIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spiderMessageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
        );

        projectsAndSpidersPanel.addTab("Schedule spiders", jPanel2);

        selectedProjectLabel.setText("Selected Project:");

        apiKeyLabel.setText("API Key:");

        jMenu1.setText("Datei");
        jMenu1.setActionCommand("Datei");

        jMenuItem1.setText("Einstellungen");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar.add(jMenu1);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(projectsAndSpidersPanel)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectedProjectLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apiKeyLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(projectsAndSpidersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectedProjectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apiKeyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listSpidersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listSpidersBtnActionPerformed
        try {
            Process p;
            String cmd[] = {"python",  "alljobids.py", "--apikey=" + this.key, "--project=" + this.projectId};
            p = Runtime.getRuntime().exec(cmd);
            BufferedReader br = new BufferedReader(new InputStreamReader(p.getInputStream()));
            String s = br.readLine();
            String[] value = ResponseParser.getCleanStringArray(s);
            spidersList.setListData(value);
        } catch (Exception ex) {
            Logger.getLogger(RunPythonScript.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listSpidersBtnActionPerformed

    private void listResultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listResultsBtnActionPerformed
        int selectedSpider = spidersList.getSelectedIndex();
        if(selectedSpider == -1) {
            JOptionPane.showMessageDialog(this, "Please select a spider.",
                    "No Selection", JOptionPane.ERROR_MESSAGE);
        }
        else {
            try {
                Process p;
                String spider = spidersList.getSelectedValue().toString();
                String cmd[] = {"python", "allitems.py", "--apikey=" + this.key, "--spider=" + spider};
                p = Runtime.getRuntime().exec(cmd);            
                BufferedReader br = new BufferedReader(new InputStreamReader(p.getInputStream()));
                String s = "[";
                s += br.readLine();
                while(true) {
                    if(s == null)
                        break;
                    String oldContent = resultArea.getText();
                    //byte[] converttoBytes = oldContent.getBytes(Charset.forName("UTF-8"));
                    //oldContent = new String(converttoBytes, "UTF-8"); //Umlaute Konvertieren -> Funktioniert nicht
                    resultArea.setText(oldContent + "\n" + s+", ");
                    s = br.readLine();
                }
                resultArea.setText(resultArea.getText().substring(0, resultArea.getText().length()-2));
                resultArea.setText(resultArea.getText()+"]");
                
            } catch (Exception ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        saveResultBtn.setEnabled(true);
    }//GEN-LAST:event_listResultsBtnActionPerformed

    private void runSpiderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runSpiderBtnActionPerformed
        try {   
            Process p;
            String cmd = "curl -u " + this.key + ": https://dash.scrapinghub.com/api/run.json -d project=" 
                    + this.projectId + " -d spider=" + this.spiderNameField.getText();
            System.out.println(cmd);
            p = Runtime.getRuntime().exec(cmd);
            BufferedReader br = new BufferedReader(new InputStreamReader(p.getInputStream()));
            this.spiderIdField.setEnabled(true);
            this.showLogBtn.setEnabled(true);
             while(true) {
                    String s = br.readLine();
                    if(s == null)
                        break;
                    String oldContent = returnTestArea.getText();
                    returnTestArea.setText(oldContent + "\n" + s);
                }
        }   catch (Exception ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_runSpiderBtnActionPerformed

    private void showLogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLogBtnActionPerformed
        Thread t = new Thread(new LogViewer(spiderIdField.getText(), this.key));
        t.start();
    }//GEN-LAST:event_showLogBtnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new Einstellungen().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void saveResultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveResultBtnActionPerformed
        AddElementToCollection save = new AddElementToCollection();
        save.addToCollection(resultArea.getText());
    }//GEN-LAST:event_saveResultBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apiKeyLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton listResultsBtn;
    private javax.swing.JButton listSpidersBtn;
    private javax.swing.JTabbedPane projectsAndSpidersPanel;
    private javax.swing.JTextArea resultArea;
    private javax.swing.JTextArea returnTestArea;
    private javax.swing.JButton runSpiderBtn;
    private javax.swing.JButton saveResultBtn;
    private javax.swing.JLabel selectedProjectLabel;
    private javax.swing.JButton showLogBtn;
    private javax.swing.JTextField spiderIdField;
    private javax.swing.JLabel spiderMessageLabel;
    private javax.swing.JTextField spiderNameField;
    private javax.swing.JList spidersList;
    // End of variables declaration//GEN-END:variables
}
